name: 🐞 Bug Report
description: Let us know about something unexpected that has happened
title: '[Bug]: '
labels: ['Bug', 'Rota']
projects: ['raizora/dev']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for letting us know something has happened.

        If this is urgent, please email report@raizora.com, or let us know on our chat channel.

        Before raising a bug, have a [search through our current issues](https://github.com/raizora/issues)
        and if the issue has already been raised add to the discussion there! If something has been marked as `wontfix`
        please still add to the issue and let us know, `wontfix` just meant `wontfix` at the time.

        The benefit of an issue is that we have a written record of what is going on and be a reference for future travelers.
        Please still reach out to facilitate discussion or in case we miss it - we're a lovely bunch!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: And what should have happened? Please provide screenshots if they would help debug and resolve this
  - type: input
    id: where
    attributes:
      label: Where is this happening?
      description: If possible please provide a URL where we can see this happening
  - type: textarea
    id: impact
    attributes:
      label: What is the impact?
      description: How far reaching is the issue, and how is it affecting their experience?